= SSH Playground

Playing around with ssh config and commands

== SSH Installation
=== 1. Update your Linux System
[source,sh]
sudo apt update

=== 2. Install SSH client and server latest versions
[source,sh]
sudo apt install ssh

== SSH Key Pair
=== 1. Create SSH key pair in your local machine
[source,sh]
ssh-keygen -t rsa -b 4096 -f ~/.ssh/playground

We have created a *4096 bits* length *RSA* type key in the *~/.ssh/playground* file.

=== 2. Copy public key to the server
There are 2 ways to add the public key to our server: MANUALLY or using *ssh-copy-id* command.

==== A. Do it MANUALLY with *scp* command:
[source,sh]
scp ~/ssh/playground.pub user@[server_ip]:/home/user/.ssh/uploaded_playground.pub

* Add the public key to authorized keys:

With the following command, copy the key to the authorized_keys file:
[source,sh]
cat ~/.ssh/uploaded_playground.pub >> ~/.ssh/authorized_keys

* Ensure the directory and files permissions:
* SSH directory must be 700:
[source,sh]
chmod 700 ~/.shh

* SSH files must be 600:
[source,sh]
chmod 600 ~/.ssh/*

==== B. Do it with SSH-COPY-ID command:
[source,sh]
ssh-copy-id user@[server_ip]

=== 3. Try to log in via SSH to the server
[source,sh]
ssh user@[server_ip]

You should be able to log into the server without being asked for a password.

=== 4. Make it persistent
If you reboot your local machine, the next time you try to access by ssh, it will ask for the user's password again. WHY??!!

This is because the ssh-agent key addition is TRANSIENT, so every time you reboot you have to restart the ssh-agent and add the custom named keys again.

This is not something you are willing to do everytime you start your computer, moreover if you have a bunch of keys, so we can add a last step where you edit the *~/.ssh/config* file with the following:
[source,sh]
AddKeysToAgent yes
IdentityFile ~/.ssh/playground

* The *AddKeysToAgent* option with a value of yes tells the SSH agent to automatically add keys upon startup.
* The *IdentityFile* specifies the private key file to be checked.

Even of you want the key to be checked just for a custom Host you can set it like:
[source,sh]
AddKeysToAgent yes
Host myHost
    IdentityFile ~/.ssh/playground


== SSH Custom Port

=== 1. Configure the server
In the server, go to */etc/ssh/sshd_config* and change the *#Port 22* line as follows:
[source,sh]
Port [custom_port]

Now restart the ssh service to apply changes:
[source,sh]
sudo service ssh restart

From your local machine, access the server with the custom port using the *-p* flag as follows:
[source,sh]
ssh -p [custom_port] user@[server_ip]

=== 2. Set the custom port as default
On your local machine, go to *~/.ssh/config* and set the port for the server:
[source,sh]
AddKeysToAgent yes
Host myHost
    IdentityFile ~/.ssh/playground
    Port [custom_port]

Save the file and use the *ssh* command without the *-p* flag.

== Firewall Stuff
We wil be using *UFW* so make sure you have it installed, or install it if you don't have it:
[source,sh]
sudo apt update
sudo apt install ufw

=== 1. Allow Only Access from Your Machine IP Address
[source,sh]
sudo ufw allow from <your_ip_address> to any port 12345

=== 2. Enable the Firewall
[source,sh]
sudo ufw enable

You can check the rules with:
[source,sh]
sudo ufw status

Now you should be able to access the server ONLY from your local machine whenever it has assigned the said IP address.
