= SSH Playground

Playing around with ssh config and commands

== SSH Installation
=== 1. Update your Linux System:
[source,sh]
sudo apt update

=== 2. Install SSH client and server latest versions:
[source,sh]
sudo apt install ssh

== SSH Key Pair
=== 1. Create SSH key pair in your local machine:
[source,sh]
ssh-keygen -t rsa -b 4096 -f ~/.ssh/playground

We have created a *4096 bits* length *RSA* type key in the *~/.ssh/playground* file.

=== 2. Copy public key to the server:
==== 2.1. Do it MANUALLY with *scp* or *rsync*:
[source,sh]
scp ~/ssh/playground.pub user@[server_ip]:/home/user/.ssh/uploaded_playground.pub

==== 2.2. Do it with SSH-COPY-ID command:
[source,sh]
ssh-copy-id user@[server_ip]

=== 3. Add the public key to authorized keys
==== 3.1. With the following command, copy the key to the authorized_keys file:
[source,sh]
cat ~/.ssh/uploaded_playground.pub >> ~/.ssh/authorized_keys

==== 3.2. Ensure the directory and files permissions:
* SSH directory must be 700:
[source,sh]
chmod 700 ~/.shh

* SSH files must be 600:
chmod 600 ~/.ssh/*

==== 3.3. Try to log in via SSH to the server:
[source,sh]
ssh user@[server_ip]

You should be able to log into the server without being asked for a password.

=== 4. Make it persistent
If you reboot your local machine, the next time you try to access by ssh, it will ask for the user's password again. WHY??!!

This is because the ssh-agent key addition is TRANSIENT, so every time you reboot you have to restart the ssh-agent and add the custom named keys again.

This is not something you are willing to do everytime you start your computer, moreover if you have a bunch of keys, so we can add a last step where you edit the *~/.ssh/config* file with the following:
[source,sh]
AddKeysToAgent yes
IdentityFile ~/.ssh/playground

* The *AddKeysToAgent* option with a value of yes tells the SSH agent to automatically add keys upon startup.
* The *IdentityFile* specifies the private key file to be checked.

Even of you want the key to be checked just for a custom Host you can set it like:
[source,sh]
AddKeysToAgent yes
Host myHost
    IdentityFile ~/.ssh/playground